var favicons = require('favicons');
var fs = require('fs');
var mkdirp = require('mkdirp');

var configuration = {
  appName: 'GongFu Timer',
  appDescription: 'A timer application for use in GongFu tea sessions.',
  developerName: 'Stijn Ruts',
  background: "#FFFFFF",
  path: "/favicons/",
  icons: {
    android: true,
    appleIcon: true,
    appleStartup: true,
    coast: true,
    favicons: true,
    firefox: true,
    windows: true,
    yandex: true
  }
};

var source = './favicons/favicon.svg';
var destination = './public/favicons/';
var component = './src/Favicons.jsx';

var template =`
  // Do not edit this file
  // It is generated with 'npm run favicons'
  import React from 'react';
  import Helmet from 'react-helmet';
  export default <Helmet>%s</Helmet>;
`;

var callback = function (error, response) {

  if (error) {
    throw error;
  }

  if (response.images) {
    mkdirp.sync(destination);
    response.images.forEach(
      image => fs.writeFileSync(destination + image.name, image.contents)
    );
  }

  if (response.files) {
    mkdirp.sync(destination);
    response.files.forEach(
      file => fs.writeFileSync(destination + file.name, file.contents)
    );
  }

  if (response.html) {
    var tags = response.html;
    tags = tags.map(tag => tag.replace(/([^\/])>/, '$1/>'));
    var content = template.replace('%s', tags.join('\n'));
    fs.writeFileSync(component, content);
  }
};

favicons(source, configuration, callback);
