var favicons = require('favicons');
var fs = require('fs');
var mkdirp = require('mkdirp');

var source = './favicons/favicon.svg';
var configuration = {
  path: "/favicons/",
  appName: 'GongFu Timer',
  apShortName: 'GongFu',
  appDescription: 'A timer application for use in GongFu tea sessions.',
  developerName: 'Doni Crosby',
  dir: "auto",
  lang: "en-US",
  background: "#FFFFFF",
  theme_color: "#000000",
  appleStatusBarStyle: "black-translucent",
  display: "standalone",
  orientation: "any",
  scope: "/",
  start_url: "./index.html",
  version: "0.2.0",
  logging: false,
  pixel_art: false,
  loadManifestWithCredentials: false,
  icons: {
    android: true,
    appleIcon: true,
    appleStartup: true,
    coast: true,
    favicons: true,
    firefox: true,
    windows: true,
    yandex: true
  }
};

var destination = './public/favicons/';
var component = './src/Favicons.jsx';

var template =`
  // Do not edit this file
  // It is generated with 'npm run favicons'
  import React from 'react';
  import Helmet from 'react-helmet';
  export default <Helmet>%s</Helmet>;
`;

var callback = function (error, response) {

  if (error) {
    throw error;
  }

  if (response.images) {
    mkdirp.sync(destination);
    response.images.forEach(
      image => fs.writeFileSync(destination + image.name, image.contents)
    );
  }

  if (response.files) {
    mkdirp.sync(destination);
    response.files.forEach(
      file => fs.writeFileSync(destination + file.name, file.contents)
    );
  }

  if (response.html) {
    var tags = response.html;
    tags = tags.filter(tag => {
      if (/sizes="32x32"/.test(tag)) { return true; }
      if (/rel="(shortcut)?\s*icon"/.test(tag)) { return false; }
      return true;
    });
    tags = tags.map(tag => tag.replace(/([^\/])>/, '$1/>'));
    var content = template.replace('%s', tags.join('\n'));
    fs.writeFileSync(component, content);
  }
};

favicons(source, configuration, callback);
